### ISSUE TITLE
can0 is not created even after installing overlay.

### ISSUE THREAD

**Issue by ankurayadav** [ankurayadav/bbbandroidHAL#3]
Even though I am able to install BB-DCAN1 overlay successfully but even then can0 is not being created.
I cannot find can0 in netcfg.

**Comment by ankurayadav** [comment]
After so much try I found out that can dev kernel modules were not enabled in BBBAndroid. So, I enabled it and now can0 has appeared in netcfg.

For activating kernel modules.
$> adb shell
After entering in BBBAndroid shell
$> cd /system/vendor/lib/modules/3.8.13+/kernel/drivers/net/can/
$> insmod can-dev.ko
$> insmod c_can/c_can.ko 
$> insmod c_can/c_can_platform.ko
$> insmod vcan.ko

$> cd /system/vendor/lib/modules/3.8.13+/kernel/net/can/
$> insmod can.ko
$> insmod can-raw.ko
$> insmod can-bcm.ko

**Comment by anujdeshpande** [comment]
Nice catch !
Maybe you could suggest @hendersa to take are of that in his next release :)

**Comment by hendersa** [comment]
Because some people may be using those pins for GPIOs, I can't load those modules by default. What I can do, though, is add the module loading statements to the init.{ro.hardware}.rc file and comment them out with a note describing what they are and to comment them back in if CAN is needed.
